import type { Metadata } from "next";
import { LayoutProvider } from "@/layout/context/LayoutContext";
import "@/styles/layout/layout.scss";
import "@/styles/components/index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          id="theme-css"
          href={`/themes/d-admin-dark/theme.css`}
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
