import type { Metadata } from "next";
import { LayoutProvider } from "@/layout/context/LayoutContext";
import '@/app/globals.css';
import "@/styles/layout/layout.scss";
import "@/styles/components/index.scss";
import Layout from "@/layout/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LayoutProvider> <Layout>{children}</Layout></LayoutProvider>
  );
}
